name: aj_text_formatter
description: "aj_text_formatter lets you easily customize your content with options to change text color, size, and font"
version: 0.0.1
homepage: 'https://github.com/Aruljebaraj/aj_text_formatter'

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf
    - family: Allura
      fonts:
        - asset: assets/fonts/Allura-Regular.otf
    - family: Arizonia
      fonts:
        - asset: assets/fonts/Arizonia-Regular.ttf
    - family: ChunkFive
      fonts:
        - asset: assets/fonts/ChunkFive-Regular.otf
    - family: GrandHotel
      fonts:
        - asset: assets/fonts/GrandHotel-Regular.otf
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.otf
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster_1.3.otf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
    - family: OstrichSans
      fonts:
        - asset: assets/fonts/OstrichSans-Medium.otf
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.otf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: SEASRN
      fonts:
        - asset: assets/fonts/SEASRN.ttf
    - family: Windsong
      fonts:
        - asset: assets/fonts/Windsong.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
